### ISSUE TITLE
Tries to load client script on server platform

### ISSUE THREAD

**Issue by EngineerSmith** [game-design-driven/ptdye-plus#15]
When trying to run a dedicated server for ptdye I get the following error. `Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER`

It is trying to load a client script on the server. To fix this I believe it only needs a `@OnlyIn(Dist.CLIENT)` flag above any function/class that tries to use the imported class.

Log:
```log
[10:35:52] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
[10:35:52] [main/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: java.lang.RuntimeException: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
        Index: 4
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                2: NORMAL
                3: ASM: class net.lavabucket.hourglass.command.HourglassCommand onRegisterCommandEvent(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                4: ASM: class com.kikis.ptdyeplus.PtdyePlus$ModEventListener registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                5: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@61d3c2f
                6: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@5f7b6584
                7: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@62592864
                8: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@5ebf7ef8
                9: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@312cdd44
                10: ASM: class io.github.mortuusars.wares.event.CommonEvents$ForgeBus registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                11: ASM: class com.jesz.createdieselgenerators.Events onCommandRegister(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                12: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@357fd9a0
                13: ASM: class tschipp.carryon.events.CommonEvents onRegisterCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                14: ASM: class com.sunekaer.mods.toolkit.commands.TKCommand registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                15: ASM: net.minecraftforge.common.ForgeInternalHandler@2df2d86a onCommandsRegister(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                16: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@1ecedd63
                17: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@3ba328fc
                18: ASM: class com.jab125.mpuc.server.command.MpucCommands forgeEvent(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                19: ASM: class com.sunekaer.mods.structureexpansion.StructureExpansion registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                20: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@6cb21431
                21: ASM: class com.railwayteam.railways.forge.RailwaysImpl onCommandRegistration(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                22: ASM: class com.simibubi.create.foundation.events.CommonEvents registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                23: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@274b62de
                24: ASM: de.keksuccino.fancymenu.FancyMenu@7183e29 onRegisterServerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
                25: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@4f069691
                26: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@6dc0a345
                27: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@11af3150
                28: net.minecraftforge.eventbus.EventBus$$Lambda$4554/0x000000e001bb7228@6d0eec29
java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
        at TRANSFORMER/ptdyeplus@1.5.3+forge-1.19.2/com.kikis.ptdyeplus.commands.OpenStonecutter.<clinit>(OpenStonecutter.java:26)
        at TRANSFORMER/ptdyeplus@1.5.3+forge-1.19.2/com.kikis.ptdyeplus.PtdyePlus$ModEventListener.registerCommands(PtdyePlus.java:53)
        at TRANSFORMER/ptdyeplus@1.5.3+forge-1.19.2/com.kikis.ptdyeplus.__ModEventListener_registerCommands_RegisterCommandsEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@43.3.5/net.minecraftforge.event.ForgeEventFactory.onCommandRegister(ForgeEventFactory.java:683)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.commands.Commands.<init>(Commands.java:205)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.ReloadableServerResources.<init>(ReloadableServerResources.java:44)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.ReloadableServerResources.m_206861_(ReloadableServerResources.java:86)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:28)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.WorldStem.m_214415_(WorldStem.java:18)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.lambda$main$3(Main.java:158)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.Util.m_214652_(Util.java:775)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.Util.m_214679_(Util.java:770)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.main(Main.java:157)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 29 more

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 7 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
        at TRANSFORMER/ptdyeplus@1.5.3+forge-1.19.2/com.kikis.ptdyeplus.commands.OpenStonecutter.<clinit>(OpenStonecutter.java:26)
        at TRANSFORMER/ptdyeplus@1.5.3+forge-1.19.2/com.kikis.ptdyeplus.PtdyePlus$ModEventListener.registerCommands(PtdyePlus.java:53)
        at TRANSFORMER/ptdyeplus@1.5.3+forge-1.19.2/com.kikis.ptdyeplus.__ModEventListener_registerCommands_RegisterCommandsEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@43.3.5/net.minecraftforge.event.ForgeEventFactory.onCommandRegister(ForgeEventFactory.java:683)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.commands.Commands.<init>(Commands.java:205)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.ReloadableServerResources.<init>(ReloadableServerResources.java:44)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.ReloadableServerResources.m_206861_(ReloadableServerResources.java:86)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:28)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.WorldStem.m_214415_(WorldStem.java:18)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.lambda$main$3(Main.java:158)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.Util.m_214652_(Util.java:775)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.Util.m_214679_(Util.java:770)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.main(Main.java:157)
        ... 13 more
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 29 more

```

**Comment by jasperalani** [comment]
fixed by https://github.com/game-design-driven/ptdye-plus/commit/b6f57cff756721bfa8d6120305cb708b3796983c
